name: Monitor de Precios Llantitas

on:
  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          PYTHONUNBUFFERED: "1"
        run: python llantita_bot.py
